### ISSUE TITLE
[Epic] Reach Parity with K3s docs

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2-docs#106]
The following commits to K3s documentation need to be implemented in RKE2 docs:
- [x] https://github.com/k3s-io/docs/commit/2819b882c8a37acaaad2860afb7c3e3198bc92a4
- [x] https://github.com/k3s-io/docs/commit/2afd3dcefe8b4407de82fd6d7d143c673c0eb47e
- [x] https://github.com/k3s-io/docs/commit/b3f57eed3652215bca57ca0974872842dcb9c928
- [x] https://github.com/k3s-io/docs/commit/95fbe791c9085d8dfd4e5bbfa93381f40c071ba9
- [x] https://github.com/k3s-io/docs/commit/b5ddfcf9eb8bb21d8cbdef778d42427213b81ad5#diff-af1b4835b31f4c6876a4d5cfcab62499095b476638b4ffd846677f5a4d8749b0 (section on AddOn naming)

Additionally:
- [x] Creation of diagram similar to https://docs.k3s.io/img/k3s-architecture-ha-embedded.svg for HA RKE2
